name: sapplauz_mobile
description: SApplauz mobilna aplikacija za korisnike i blagajnike
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  file_picker: ^8.1.7
  table_calendar: ^3.1.2
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  flutter_stripe: ^11.1.0
  intl: ^0.19.0
  sapplauz_core:
    path: ../packages/sapplauz_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

